# Generated by Django 4.2.3 on 2024-05-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
