# Generated by Django 4.2.3 on 2024-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_content_options_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
