# Generated by Django 4.2.3 on 2024-05-30 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_content_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenidos'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El título debe ser de más de dos caracteres')]),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe ser de más de dos caracteres')]),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('PR', 'Presentación'), ('MA', 'Material adicional'), ('SR', 'Serie')], default='MA', max_length=30),
        ),
    ]
